import pandas as pd
df = pd.read_csv("data/raw/train.csv")
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.columns)
print(df.shape)
print(df.duplicated().sum())
print(df.drop_duplicates())
print(df.shape)
df.to_csv("data/cleaned/cleaned_train.csv", index=False)
print("Data cleaning completed and saved to cleaned_train.csv")
df["Order Date"] = pd.to_datetime(df["Order Date"],dayfirst=True)
df["Ship Date"] = pd.to_datetime(df["Ship Date"],dayfirst=True)
df = df.drop_duplicates()
df.to_csv("data/cleaned/cleaned_train.csv", index=False)
print(df.dtypes)
print(df.head())
df["year"] = df["Order Date"].dt.year
df["month"] = df["Order Date"].dt.month
df["quarter"] = df["Order Date"].dt.quarter
print(df[["Order Date", "year", "month", "quarter"]].head())
print("total sales:", df["Sales"].sum())

#print("total quantity:", df["Quantity"].sum())
print("total orders:", df["Order ID"].nunique())
print("sales by category:", df.groupby("Category")["Sales"].sum())
#print("profit by category:", df.groupby("Category")["Profit"].sum())
print("sales by sub-category:", df.groupby("Sub-Category")["Sales"].sum())
#print("profit by sub-category:", df.groupby("Sub-Category")["Profit"].sum())
print("sales by region:", df.groupby("Region")["Sales"].sum())
#print("profit by region:", df.groupby("Region")["Profit"].sum())
print("top 10 states by sales:", df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(10))
df["month"] = df["Order Date"].dt.to_period("M")
monthly_sales = df.groupby("month")["Sales"].sum()
print("monthly sales:", monthly_sales)
print("top 10 products by sales:", df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10))
print("top 10 customers by sales:", df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10))
#print("most profitable products:", df.groupby("Product Name")["Profit"].sum().sort_values(ascending=False).head(10))
#print("least profitable products:", df.groupby("Product Name")["Profit"].sum().sort_values(ascending=True).head(10))
print("sales by ship mode:", df.groupby("Ship Mode")["Sales"].sum())
print("sales by segment:", df.groupby("Segment")["Sales"].sum())
#print("average discount", df["Discount"].mean())
#print("correlation between sales and profit:", df["Sales"].corr(df["Profit"]))
#print("correlation between sales and quantity:", df["Sales"].corr(df["Quantity"]))
#print("correlation between profit and quantity:", df["Profit"].corr(df["Quantity"]))
print("analysis completed.")